baseURL = 'https://kayigis.github.io/capek/'
languageCode = 'en-us'
title = "Petra's site"   

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"

[params]
  # color style
  color = 'wheat'                           # linen, wheat, gray, light
  github = 'Kayigis'
  name = 'Petra'
  bio = '"It is finished"'
  avatar = 'https://github.com/Kayigis/capek/blob/main/static/images/Avatars.webp'

[menu]

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10
